function data = gatherData()
global KRPC;
persistent T0;
if(isempty(T0))
    T0 = 0;
end
while(KRPC.Vessel.getMET() == T0)
    pause(0);
end
data = [ ...
        KRPC.Vessel.getMET(),...
        KRPC.Vessel.position(KRPC.referframe_ground),...
        KRPC.Vessel.velocity(KRPC.referframe_ground),...
        KRPC.Vessel.rotation(KRPC.referframe_ground),...
        KRPC.Vessel.angularVelocity(KRPC.referframe_ground),...
        KRPC.TargetVessel.position(KRPC.referframe_ground),...
        KRPC.TargetVessel.velocity(KRPC.referframe_ground)
    ];
T0 = data(1);
end